//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainCore_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaracteristicasExtraidasSet
    {
        public int Id { get; set; }
        public int idMuestra { get; set; }
        public int codigoCaracteristica { get; set; }
        public double Valor { get; set; }
    
        public virtual MuestraSet MuestraSet { get; set; }
    }
}
