//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainCore_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class MpatSet
    {
        public MpatSet()
        {
            this.CiclosEvaluacionSet = new HashSet<CiclosEvaluacionSet>();
            this.ProcedimientoClinicoSet = new HashSet<ProcedimientoClinicoSet>();
            this.ExperimentoSet = new HashSet<ExperimentoSet>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public int ciclosMasticatorios { get; set; }
        public int Estado { get; set; }
        public string DescripcionTestFood { get; set; }
        public int UsuarioSetId { get; set; }
    
        public virtual ICollection<CiclosEvaluacionSet> CiclosEvaluacionSet { get; set; }
        public virtual ICollection<ProcedimientoClinicoSet> ProcedimientoClinicoSet { get; set; }
        public virtual ICollection<ExperimentoSet> ExperimentoSet { get; set; }
    }
}
