//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainCore_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuestraSet
    {
        public MuestraSet()
        {
            this.CaracteristicasExtraidasSet = new HashSet<CaracteristicasExtraidasSet>();
        }
    
        public int Id { get; set; }
        public int CiclosMasticatorios { get; set; }
        public int idPaciente { get; set; }
        public int idExperimento { get; set; }
        public string lado { get; set; }
    
        public virtual ICollection<CaracteristicasExtraidasSet> CaracteristicasExtraidasSet { get; set; }
        public virtual ExperimentoSet ExperimentoSet { get; set; }
    }
}
