//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaClinica
    {
        public HistoriaClinica()
        {
            this.Paciente = new HashSet<Paciente>();
        }
    
        public int Id { get; set; }
        public string odontograma { get; set; }
        public int numeroCariados { get; set; }
        public int numeroDientesPerdidos { get; set; }
        public int numeroDientesObturados { get; set; }
        public string ortodoncia { get; set; }
        public string protesis { get; set; }
        public int implantes { get; set; }
        public int paresAntagPerdidos { get; set; }
        public int gradoEdentulismo { get; set; }
        public bool estadoSaludGeneral { get; set; }
        public bool enfermedadCardioVascular { get; set; }
        public bool enfermedadRenal { get; set; }
        public bool ICTUS { get; set; }
        public bool ACV { get; set; }
        public bool paralisisFacial { get; set; }
        public int gradoDesnutricion { get; set; }
    
        public virtual ICollection<Paciente> Paciente { get; set; }
    }
}
