//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainCore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container1 : DbContext
    {
        public Model1Container1()
            : base("name=Model1Container1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CaracteristicaMedida> CaracteristicaMedidaSet { get; set; }
        public virtual DbSet<Experimento> ExperimentoSet { get; set; }
        public virtual DbSet<HistoriaClinica> HistoriaClinicaSet { get; set; }
        public virtual DbSet<Mpat> MpatSet { get; set; }
        public virtual DbSet<Muestra> MuestraSet { get; set; }
        public virtual DbSet<Paciente> PacienteSet { get; set; }
        public virtual DbSet<ProcedimientoClinico> ProcedimientoClinicoSet { get; set; }
        public virtual DbSet<Pruebas> PruebasSet { get; set; }
        public virtual DbSet<TestFood> TestFoodSet { get; set; }
        public virtual DbSet<TipoTestFood> TipoTestFoodSet { get; set; }
        public virtual DbSet<CiclosEvaluacion> CiclosEvaluacionSet { get; set; }
    }
}
