//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muestra
    {
        public Muestra()
        {
            this.CaracteristicaMedidaSet = new HashSet<CaracteristicaMedida>();
            this.PacienteSet = new HashSet<Paciente>();
        }
    
        public int Id { get; set; }
        public string Ciclos { get; set; }
    
        public virtual ICollection<CaracteristicaMedida> CaracteristicaMedidaSet { get; set; }
        public virtual ICollection<Paciente> PacienteSet { get; set; }
    }
}
