//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metodos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muestra
    {
        public Muestra()
        {
            this.Paciente = new HashSet<Paciente>();
            this.CaracteristicaMedida = new HashSet<CaracteristicaMedida>();
        }
    
        public int Id { get; set; }
        public string Ciclos { get; set; }
    
        public virtual ICollection<Paciente> Paciente { get; set; }
        public virtual ICollection<CaracteristicaMedida> CaracteristicaMedida { get; set; }
    }
}
