//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AiGumsPC.srvweb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvweb.INegocioService")]
    public interface INegocioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INegocioService/DoWork", ReplyAction="http://tempuri.org/INegocioService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INegocioService/DoWork", ReplyAction="http://tempuri.org/INegocioService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INegocioService/login", ReplyAction="http://tempuri.org/INegocioService/loginResponse")]
        bool login(string Usuario, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INegocioService/login", ReplyAction="http://tempuri.org/INegocioService/loginResponse")]
        System.Threading.Tasks.Task<bool> loginAsync(string Usuario, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INegocioService/procesoValidacionMPAT", ReplyAction="http://tempuri.org/INegocioService/procesoValidacionMPATResponse")]
        AiGumsPC.srvweb.procesoValidacionMPATResponse procesoValidacionMPAT(AiGumsPC.srvweb.procesoValidacionMPATRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INegocioService/procesoValidacionMPAT", ReplyAction="http://tempuri.org/INegocioService/procesoValidacionMPATResponse")]
        System.Threading.Tasks.Task<AiGumsPC.srvweb.procesoValidacionMPATResponse> procesoValidacionMPATAsync(AiGumsPC.srvweb.procesoValidacionMPATRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="procesoValidacionMPAT", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class procesoValidacionMPATRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public LibreriaObjetos.S_Mpat mpat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public double[][] listaVectoresCaracteristicas;
        
        public procesoValidacionMPATRequest() {
        }
        
        public procesoValidacionMPATRequest(LibreriaObjetos.S_Mpat mpat, double[][] listaVectoresCaracteristicas) {
            this.mpat = mpat;
            this.listaVectoresCaracteristicas = listaVectoresCaracteristicas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="procesoValidacionMPATResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class procesoValidacionMPATResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool procesoValidacionMPATResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public double[] vector;
        
        public procesoValidacionMPATResponse() {
        }
        
        public procesoValidacionMPATResponse(bool procesoValidacionMPATResult, double[] vector) {
            this.procesoValidacionMPATResult = procesoValidacionMPATResult;
            this.vector = vector;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INegocioServiceChannel : AiGumsPC.srvweb.INegocioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NegocioServiceClient : System.ServiceModel.ClientBase<AiGumsPC.srvweb.INegocioService>, AiGumsPC.srvweb.INegocioService {
        
        public NegocioServiceClient() {
        }
        
        public NegocioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NegocioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NegocioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NegocioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public bool login(string Usuario, string Password) {
            return base.Channel.login(Usuario, Password);
        }
        
        public System.Threading.Tasks.Task<bool> loginAsync(string Usuario, string Password) {
            return base.Channel.loginAsync(Usuario, Password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AiGumsPC.srvweb.procesoValidacionMPATResponse AiGumsPC.srvweb.INegocioService.procesoValidacionMPAT(AiGumsPC.srvweb.procesoValidacionMPATRequest request) {
            return base.Channel.procesoValidacionMPAT(request);
        }
        
        public bool procesoValidacionMPAT(LibreriaObjetos.S_Mpat mpat, double[][] listaVectoresCaracteristicas, out double[] vector) {
            AiGumsPC.srvweb.procesoValidacionMPATRequest inValue = new AiGumsPC.srvweb.procesoValidacionMPATRequest();
            inValue.mpat = mpat;
            inValue.listaVectoresCaracteristicas = listaVectoresCaracteristicas;
            AiGumsPC.srvweb.procesoValidacionMPATResponse retVal = ((AiGumsPC.srvweb.INegocioService)(this)).procesoValidacionMPAT(inValue);
            vector = retVal.vector;
            return retVal.procesoValidacionMPATResult;
        }
        
        public System.Threading.Tasks.Task<AiGumsPC.srvweb.procesoValidacionMPATResponse> procesoValidacionMPATAsync(AiGumsPC.srvweb.procesoValidacionMPATRequest request) {
            return base.Channel.procesoValidacionMPATAsync(request);
        }
    }
}
